# ===============================
# n8n + Nginx HTTPS Proxy Deployment
#
# 1. Generate a self-signed certificate (if you haven't already):
#    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
#      -keyout artifacts/nginx-selfsigned.key \
#      -out artifacts/nginx-selfsigned.crt \
#      -subj "/CN=localhost"
#
# 2. Make sure your n8n stack is running and on the 'infernet' network.
#
# 3. Start the nginx proxy:
#    docker compose -f docker-compose.nginx.yaml up -d
#    docker compose -f docker-compose.nginx.yaml down # Stop the nginx proxy
#    docker compose -f docker-compose.nginx.yaml down && docker compose -f docker-compose.nginx.yaml up -d # Stop and start the nginx proxy
#
# 4. Access n8n securely at:
#    https://localhost/  (or https://<your-server-ip>/)
#
# ===============================

version: '3.8'

services:
  nginx:
    image: nginx:1.28.0-alpine3.21
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./artifacts/n8n.local/n8n.local.conf:/etc/nginx/conf.d/default.conf:ro
      - ./artifacts/n8n.local/n8n.local.crt:/etc/nginx/certs/n8n.local.crt:ro
      - ./artifacts/n8n.local/n8n.local.key:/etc/nginx/certs/n8n.local.key:ro
    networks:
      - infernet

networks:
  infernet:
    external: true



